import sys, os
sys.path.append( os.path.join( os.path.dirname(__file__), '..' ) )
import PyULIS2 as ul2

block = ul2.FBlock( 256, 256, ul2.Format_RGBA8 )
print( block.Width() )
print( block.Height() )
print( block.Format() )
print( block.BytesPerSample() )
print( block.BytesPerPixel() )
print( block.BytesPerScanLine() )
print( block.BytesTotal() )
print( block.Model() )
print( block.Type() )
print( block.HasAlpha() )
print( block.Swapped() )
print( block.Reversed() )
print( block.SamplesPerPixel() )
print( block.NumColorChannels() )
print( block.AlphaIndex() )
print( block.CRC32() )
print( block.MD5() )
print( block.UUID() )
print( block.TypeStr() )
print( block.ModelStr() )
